[env]
TERM = "xterm-256color"

[window]
padding.x = 6
padding.y = 6
decorations = "None"
opacity = 0.95

[font]
normal.family = 'Hack Nerd Font Mono'
bold.family   = 'Hack Nerd Font Mono'
italic.family = 'Hack Nerd Font Mono'
size = 10

[terminal.shell]
program = "/bin/bash"
args = ["-l"]

[keyboard]
bindings = [
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

# Kanagawa Wave color scheme
[colors.primary]
background = "#1f1f28"
foreground = "#dcd7ba"

[colors.cursor]
text   = "#c8c093"
cursor = "#c8c093"

[colors.normal]
black   = "#090618"
red     = "#c34043"
green   = "#76946a"
yellow  = "#c0a36e"
blue    = "#7e9cd8"
magenta = "#957fb8"
cyan    = "#6a9589"
white   = "#c8c093"

[colors.bright]
black   = "#727169"
red     = "#e82424"
green   = "#98bb6c"
yellow  = "#e6c384"
blue    = "#7fb4ca"
magenta = "#938aa9"
cyan    = "#7aa89f"
white   = "#dcd7ba"

[colors.selection]
background = "#2d4f67"
foreground = "#c8c093"
