#!/bin/bash

# Enable the subsequent settings only in interactive sessions
case $- in
  *i*) ;;
    *) return;;
esac

# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="mm/dd/yyyy"

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# # Set personal aliases, overriding those provided by oh-my-bash libs,
# plugins, and themes. Aliases can be placed here, though oh-my-bash
# users are encouraged to define aliases within the OSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
if [ -r ~/.bash_profile ]; then
    . ~/.bash_profile
fi

# Set dircolors config path
DIRCOLORS_PATH="$HOME/.config/dir_colors/colors"

if [[ "$(uname)" == "Darwin" ]]; then
  # macOS
  if command -v gdircolors >/dev/null 2>&1 && [[ -f "$DIRCOLORS_PATH" ]]; then
    eval "$(gdircolors -b "$DIRCOLORS_PATH")"
  fi

  if command -v gls >/dev/null 2>&1; then
    alias ls='gls --color=auto'
  fi
else
  # Linux
  if command -v dircolors >/dev/null 2>&1 && [[ -f "$DIRCOLORS_PATH" ]]; then
    eval "$(dircolors -b "$DIRCOLORS_PATH")"
  fi

  alias ls='ls --color=auto'
fi

# Sets title to new terminals (windows/tabs)
# https://askubuntu.com/a/886695
set-title() {
    if [[ -z "$ORIG" ]]; then
        ORIG="$PS1"
    fi
    TITLE="\[\e]2;$*\a\]"
    PS1="${ORIG}${TITLE}"
}
# Title I want: '(FirstFolderInPath) LastFolderInPath'
set-title "($(pwd | cut -d/ -f2)) ${PWD##*/}"

. "$HOME/.cargo/env"


# --- tmux window renaming ---
update_tmux_window_name() {
  [[ -z "$TMUX" ]] && return  # Only run inside tmux

  local name="$(basename "$PWD")"

  if git rev-parse --is-inside-work-tree &>/dev/null; then
    local branch
    branch=$(git symbolic-ref --short HEAD 2>/dev/null || git describe --tags --exact-match 2>/dev/null)
    if [[ -n "$branch" ]]; then
      name+=" ($branch)"
    fi
  fi

  tmux rename-window "$name"
}

# Fix terminal control characters (e.g., Ctrl+A, Ctrl+L)
stty sane

# Run on every prompt
# PROMPT_COMMAND="update_tmux_window_name; $PROMPT_COMMAND"

# Generated for envman. Do not edit.
[ -s "$HOME/.config/envman/load.sh" ] && source "$HOME/.config/envman/load.sh"

# The next line updates PATH for the Google Cloud SDK.
if [ -f "$HOME/Downloads/google-cloud-sdk/path.bash.inc" ]; then . "$HOME/Downloads/google-cloud-sdk/path.bash.inc"; fi

# The next line enables shell command completion for gcloud.
if [ -f "$HOME/Downloads/google-cloud-sdk/completion.bash.inc" ]; then . "$HOME/Downloads/google-cloud-sdk/completion.bash.inc"; fi

# Turso
if [ -d "$HOME/.turso" ]; then export PATH="$PATH:$HOME/.turso"; fi
