#!/bin/bash

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cd..="cd .."

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias cp="cp -iv"
#             │└─ list copied files
#             └─ prompt before overwriting an existing file

alias mkdir="mkdir -pv"
#                   │└─ list created directories
#                   └─ create intermediate directories

alias mv="mv -iv"
#             │└─ list moved files
#             └─ prompt before overwriting an existing file


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias :q="exit"
alias q="exit"
alias c="clear"
alias d="cd ~/Desktop"
alias dt="cd ~/dotfiles"
alias doc="cd ~/Documents"
alias dow="cd ~/Downloads/"
alias g="git"
alias whatsmyip="dig +short myip.opendns.com @resolver1.opendns.com"
alias ll="ls -lh"
alias m="man"
alias t="tldr"
alias n="npm"
alias p="cd ~/projects"
alias y="yarn"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias empty-trash="rm -rf ~/.local/share/Trash/files/*"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Open from the terminal.

alias o="xdg-open"

# Make some possibly destructive commands more interactive.
#alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'
alias rm='~/bin/new-rm.sh'
alias unrm='~/bin/unrm.sh'
alias python=python3
alias nano='nano -ET2'

# Add some easy shortcuts for formatted directory listings and add a touch of color.
alias ll='ls -lisa --color'
alias la='ls -alF --color'
alias ls='ls -F'

# Make grep more user friendly by highlighting matches
# and exclude grepping through .svn folders.
alias grep='grep --color=auto --exclude-dir=\.svn'
alias ripgrep=rg

# Shortcut for using the Kdiff3 tool for svn diffs.
alias svnkdiff3='svn diff --diff-cmd kdiff3'

# nvim
alias n='nvim .'
