#!/bin/bash
# https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html

# ==== History Configuration ====
export HISTCONTROL=ignoreboth:ignoredups
export HISTFILESIZE=10000
export HISTSIZE=10000
export HISTIGNORE="&:[bf]g:c:clear:history:exit:q:pwd:* --help"
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# ==== Locale / Encoding ====
export PYTHONIOENCODING="UTF-8"
# export LANG=en_US.UTF-8
# export LC_ALL=en_US.UTF-8

# ==== Man Page & Less ====
export LESS_TERMCAP_md="$(tput bold 2>/dev/null)$(tput setaf 2 2>/dev/null)"
export LESS_TERMCAP_me="$(tput sgr0 2>/dev/null)"
export MANPAGER="less -X"

# ==== Node.js ====
export NODE_REPL_HISTORY_SIZE=10000
NPM_PACKAGES="${HOME}/.npm-packages"
export PATH="$PATH:$NPM_PACKAGES/bin"
export MANPATH="${MANPATH-$(manpath)}:$NPM_PACKAGES/share/man"

# ==== fzf ====
export FZF_IGNORES=Applications,Library,Movies,Music,Pictures,Qt,node_modules,venv,.DS_Store,.Trash,.cache,.git,.mypy_cache,.npm,.pyenv,.pytest_cache,.stack,.temp,__pycache__
export FZF_DEFAULT_COMMAND='command fd --hidden --no-ignore --exclude "{$FZF_IGNORES}" .'
export FZF_DEFAULT_OPTS='--ansi --preview "bat --color=always --style=header,grid --line-range :300 {}"'
export FZF_ALT_C_COMMAND='command fd --type d --type l --hidden --no-ignore --exclude "{$FZF_IGNORES}" .'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_COMPLETION_TRIGGER='**'

# ==== Shell ====
export SHELL="/bin/bash"
export BASH_SILENCE_DEPRECATION_WARNING=1

# ==== Directory Locations ====
export XDG_CONFIG_HOME="$HOME/.config"
export TMUX_CONF="$XDG_CONFIG_HOME/tmux/tmux.conf"
export SSH_KEY_PATH="$HOME/.ssh/rsa_id"

# ==== Language & Toolchains ====

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

# poetry
export PATH="$HOME/.poetry/bin:$PATH"

# deno
export DENO_INSTALL="$HOME/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"

# go
export GOPATH="$HOME/repos/golang/src/github.com/rnemeth90"
export GOBIN="$HOME/repos/golang/bin"
export PATH="$GOBIN:$GOPATH/bin:$PATH"
# export GOPATH="$HOME/repos/golang"
export GOMODCACHE="$HOME/.cache/go/pkg/mod"

# dotnet
export DOTNET_ROOT="/usr/local/share/dotnet"
export PATH="$DOTNET_ROOT:$PATH"

# krew / Kubernetes
export KUBE_EDITOR=nvim
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

# rust / cargo
export PATH="${CARGO_ROOT:-$HOME/.cargo}/bin:$PATH"

# ==== System PATH Setup ====

# Homebrew / Coreutils / local bin
export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:/opt/homebrew/bin:$HOME/bin:/usr/local/bin:/usr/local/go/bin:/opt/julia/julia-1.8.5/bin:$PATH"

# Add any /usr/bin/*/bin dynamically
for d in /usr/bin/*/bin; do PATH="$PATH:$d"; done
