#!/bin/bash
enable_color_support() {

    if [[ $COLORTERM == gnome-* && $TERM == xterm ]] \
        && infocmp gnome-256color &> /dev/null; then
        export TERM="gnome-256color"
    elif infocmp xterm-256color &> /dev/null; then
        export TERM="xterm-256color"
    fi

    source ./bash_colors
}

function set_win_title(){
    echo -ne "\033]0; $(basename "$PWD") \007"
}

function parse_git_branch() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

main() {
  export PS1=" \[\e[00;34m\]λ \W \[\e[0m\]$ "
  # export PS1="\u@\h \[\e[32m\]\w \[\e[91m\]\$(parse_git_branch)\[\e[00m\]$ "
}
main

