#!/bin/bash

# Enable the subsequent settings only in interactive sessions
case $- in
  *i*) ;;
    *) return;;
esac

# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="mm/dd/yyyy"

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# # Set personal aliases, overriding those provided by oh-my-bash libs,
# plugins, and themes. Aliases can be placed here, though oh-my-bash
# users are encouraged to define aliases within the OSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
if [ -L ~/.bash_profile ]; then
    . ~/.bash_profile
fi

# Source files from my aliases directory
aliases_dir=~/.bash_aliases.d
if [[ -d $aliases_dir && -r $aliases_dir && -x $aliases_dir ]]; then
    for i in "$aliases_dir"/*; do
        [[ -f $i && -r $i ]] && . "$i"
    done
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Sets title to new terminals (windows/tabs)
# https://askubuntu.com/a/886695
set-title() {
    if [[ -z "$ORIG" ]]; then
        ORIG="$PS1"
    fi
    TITLE="\[\e]2;$*\a\]"
    PS1="${ORIG}${TITLE}"
}
# Title I want: '(FirstFolderInPath) LastFolderInPath'
set-title "($(pwd | cut -d/ -f2)) ${PWD##*/}"

