#!/bin/bash

if command -v dircolors >/dev/null 2>&1; then
    if [ -f "$HOME/.config/dircolors/colors" ]; then
        eval "$(dircolors -b "$HOME/.config/dircolors/colors")"
    fi
    alias ls="ls --color=auto"
    alias dir="dir --color=auto"
    alias vdir="vdir --color=auto"
    alias grep="grep --color=auto"
    alias egrep="egrep --color=auto"
    alias fgrep="fgrep --color=auto"
fi
