#!/bin/bash

declare DOT=$HOME/dotfiles

source_bash_files() {

    declare -r CURRENT_DIRECTORY="$(pwd)"

    declare -r -a FILES_TO_SOURCE=(
        "fzf.bash"
        "bash_aliases"
        "bash_autocompletion"
        "bash_colors"
        "bash_exports"
        "bash_options"
        "bash_prompt"
        "bash.local"  # For local settings that should
                      # not be under version control.
    )

    local file=""
    local i=""

    cd "$(dirname "$(readlink "${BASH_SOURCE[0]}")")" \
        && . "$DOT/utils/utils.sh"

    # shellcheck disable=SC2034
    declare -r OS="$(get_os)"

    for i in ${!FILES_TO_SOURCE[*]}; do

        file="$HOME/.${FILES_TO_SOURCE[$i]}"

        [ -r "$file" ] \
            && . "$file"

    done

    cd "$CURRENT_DIRECTORY"

}

source_bash_files
unset -f source_bash_files

for f in ~/.bash_aliases.d/*; do source $f; done

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

# Created by `pipx` on 2024-05-30 19:41:22
export PATH="$PATH:/Users/Ryan.Nemeth/.local/bin"

if [[ $(tty) = /dev/tty1 ]] ; then
  startx
fi

