github.com:
    users:
        rnemeth90:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: rnemeth90
