##### General #####
set -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc,screen-256color:Tc"

set-option -g default-terminal "xterm-kitty"
set-option -ga terminal-overrides ",xterm-kitty:Tc"

set-option -g history-limit 10000
set-option -s escape-time 10
set-option -g repeat-time 300

bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"


##### Status Line #####

set-option -g status on
set-option -g status-interval 5
set-option -g status-justify centre
set-option -g status-bg colour235
set-option -g status-fg colour136
set-option -g status-left '#[fg=green]#S '
set-option -g status-right '#[fg=cyan]%Y-%m-%d #[fg=white]%H:%M:%S'
set-option -g set-titles off
set-option -g set-titles-string '#T'


##### Mouse & Copy Mode #####

set-option -g mouse on
setw -g mode-keys vi

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind -T copy-mode-vi Escape send -X cancel

# Copy selection to macOS clipboard
bind y run-shell "tmux save-buffer - | pbcopy"


##### Panes & Navigation #####

set-option -g base-index 1
setw -g pane-base-index 1

bind | split-window -h
bind - split-window -v

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind -r C-h previous-window
bind -r C-l next-window
bind Tab last-window


##### Sessions #####

bind C-c new-session
bind BTab switch-client -l


##### Theme #####
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

##### Misc #####


bind-key . run -b 'tmux rename-window "`basename \"#{pane_current_path}\"`"'

bind C-l send-keys C-l \; run-shell 'sleep 0.1' \; clear-history
setw -g automatic-rename off
set-option -g renumber-windows on
