# Environment Variables
$env:EDITOR = "nvim"
$env:TERM = "xterm-256color"

. "$PSScriptRoot/functions/conversions.ps1"
. "$PSScriptRoot/functions/env.ps1"
. "$PSScriptRoot/functions/misc.ps1"
. "$PSScriptRoot/functions/git.ps1"
. "$PSScriptRoot/functions/terraform.ps1"
. "$PSScriptRoot/functions/helm.ps1"
. "$PSScriptRoot/functions/kubernetes.ps1"
. "$PSScriptRoot/functions/docker.ps1"
. "$PSScriptRoot/functions/az.ps1"
. "$PSScriptRoot/functions/work.ps1"
. "$PSScriptRoot/functions/navigation.ps1"
. "$PSScriptRoot/functions/aliases.ps1"
