#!/bin/bash
set -e

###############################
# Run all dotfiles installers #
###############################

cd "$(dirname $0)"/..

# find the installers and run them interatively if you choose
find ../ -name install.sh -type f -exec chmod a+x {} \;
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
