[env]
TERM = "xterm-256color"

[window]
padding.x = 2
padding.y = 2

# decorations = "Buttonless"

opacity = 0.5
blur = true

option_as_alt = "Both"

[font]
normal.family = 'Hack Nerd Font Mono'
bold.family = 'Hack Nerd Font Mono'
italic.family = 'Hack Nerd Font Mono'
size = 10

[terminal.shell]
program = "/bin/bash"
args = ["-l"]

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]
