[colors]
background = #33000000
background-alt = #444
foreground = #dfdfdf
foreground-alt = #dfdfdf
primary = #ffb52a
secondary = #e60053
alert = #bd2c40

[bar/top]
monitor = ${env:MONITOR:}
width = 99.5%
height = 40
radius = 10.0
fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 1
line-color = #f00

border-size = 0
border-color = #00000000

padding-left = 0
padding-right = 2

module-margin-left = 2
module-margin-right = 2

font-0 = "Hack Nerd Font Propo:style=Regular:size=11;1"

modules-left = i3 xwindow
modules-center = mpd
modules-right = filesystem wifi battery temperature pulseaudio memory cpu date powermenu

tray-position = none
tray-padding = 2

wm-restack = i3

cursor-click = pointer
cursor-scroll = ns-resize

[bar/bottom]
monitor = ${env:MONITOR:}
width = 98%
height = 20
radius = 10.0
fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 1
line-color = #f00

border-size = 0
border-color = #00000000

padding-left = 0
padding-right = 0

module-margin-left = 2
module-margin-right = 2


modules-left = workspace
modules-center = clock
modules-right = updates disk usage

tray-position = none
tray-padding = 2

cursor-click = pointer
cursor-scroll = ns-resize

[module/xwindow]
type = internal/xwindow
label = %title:0:30:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{A1:nemo:} %free%%{A}
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.foreground-alt}

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false

ws-icon-0 = 1;
ws-icon-1 = 2;
ws-icon-2 = 3;
ws-icon-3 = 4;󰘐

label-mode-padding = 2
label-mode-foreground = #000
label-mode-background = ${colors.primary}

label-focused = %icon%
label-focused-background = ${colors.background-alt}
label-focused-padding = 2

label-unfocused = %icon%
label-unfocused-padding = 2

label-visible = %icon%
label-visible-background = ${self.label-focused-background}
label-visible-padding = ${self.label-focused-padding}

label-urgent = %icon%
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

[module/mpd]
type = internal/mpd
format-online = <label-song>  <icon-prev> <icon-stop> <toggle> <icon-next>

icon-prev = 
icon-stop = 
icon-play = 
icon-pause = 
icon-next = 

label-song-maxlen = 25
label-song-ellipsis = true

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = ""
format-prefix-foreground = ${colors.foreground-alt}
label = %percentage:2%%

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
label = %percentage_used%%
#
# [module/wlan]
# type = internal/network
# # interface = ${env:DEFAULT_NETWORK:$(ip route | grep '^default' | awk '{print $5}')}
# interface = wlan0
# interval = 3.0
#
# format-connected = 󱚿
# label-connected = %{A1:nm-connection-editor:}%essid%%{A}
#
# format-disconnected = 󱚼
# label-disconnected = %{A1:nm-connection-editor:}%essid%%{A}
#
# ramp-signal-0 = 󱛏
# ramp-signal-1 = 󱛋
# ramp-signal-2 = 󱛌
# ramp-signal-3 = 󱛍
# ramp-signal-4 = 󱛎
# ramp-signal-foreground = ${colors.foreground-alt}
#
[module/date]
type = internal/date
interval = 5

date =
date-alt = " %Y-%m-%d"

time = %H:%M
time-alt = %H:%M:%S

format-prefix = 
format-prefix-foreground = ${colors.foreground-alt}

label = %date% %time%

[module/pulseaudio]
type = internal/pulseaudio

format-volume = <label-volume> <bar-volume>
label-volume =  %percentage%

label-volume-foreground = ${root.foreground}

label-muted =  muted
label-muted-foreground = #666

bar-volume-width = 7
bar-volume-gradient = true
bar-volume-indicator = |
bar-volume-fill = ─
bar-volume-empty = ─
bar-volume-empty-foreground = ${colors.foreground-alt}

[module/battery]
type = internal/battery
battery = BAT1
adapter = AC
full-at = 98

format-charging = %{A3:$TERMINAL -e acpi -b &:}<animation-charging> <label-charging>%{A3}
format-discharging = %{A3:$TERMINAL -e acpi -b &:}<ramp-capacity> <label-discharging>%{A3}
format-full = <ramp-capacity> <label-full>

ramp-capacity-0 = 
ramp-capacity-0-foreground = #f53c3c
ramp-capacity-1 = 
ramp-capacity-1-foreground = #ffa900
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate = 750

animation-discharging-0 = 󱊣
animation-discharging-1 = 󱊢
animation-discharging-2 = 󱊡
animation-discharging-framerate = 750

[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 60

format = <ramp> <label>
format-warn = <ramp> <label-warn>

label = %temperature-f%
label-warn = %temperature-f%
label-warn-foreground = ${colors.secondary}

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-foreground = ${colors.foreground-alt}

[module/powermenu]
type = custom/menu

expand-right = true

format-spacing = 0

label-open = ""
label-open-foreground = ${colors.urgent}
label-close =  cancel
label-close-foreground = ${colors.success}
label-separator = |
label-separator-foreground = ${colors.foreground}

menu-0-0 = "Reboot"
menu-0-0-exec = menu-open-1
menu-0-0-foreground = ${colors.urgent}

menu-0-1 = "Power Off"
menu-0-1-exec = menu-open-2
menu-0-1-foreground = ${colors.urgent}

menu-0-2 = "Hibernate"
menu-0-2-exec = menu-open-3
menu-0-2-foreground = ${colors.warning}

menu-0-3 = "Lock"
menu-0-3-exec = loginctl lock-session
menu-0-3-foreground = ${colors.urgent}

menu-0-4 = "Logout"
menu-0-4-exec = i3-msg exit
menu-0-4-foreground = ${colors.urgent}

menu-1-0 = "Cancel"
menu-1-0-exec = menu-open-0
menu-1-0-foreground = ${colors.success}
menu-1-1 = "Reboot"
menu-1-1-exec = systemctl reboot
menu-1-1-foreground = ${colors.urgent}

menu-2-0 = "Power off"
menu-2-0-exec = systemctl poweroff
menu-2-0-foreground = ${colors.urgent}
menu-2-1 = "Cancel"
menu-2-1-exec = menu-open-0
menu-2-1-foreground = ${colors.success}

menu-3-0 = "Hibernate"
menu-3-0-exec = systemctl hibernate
menu-3-0-foreground = ${colors.urgent}
menu-3-1 = "Cancel"
menu-3-1-exec = menu-open-0
menu-3-1-foreground = ${colors.success}

[settings]
screenchange-reload = true
pseudo-transparency = true
compositing-background = screen

[global/wm]
margin-top = 5
margin-bottom = 5
#
# [module/bluetooth]
# type = custom/script
# exec = /home/ryan/bin/bluetooth.sh
# interval = 2
# click-left = exec blueberry
# click-right = exec /home/ryan/bin/toggle_bluetooth.sh
# format-padding = 0
# format-background = ${colors.background}
# format-foreground = ${colors.foreground}
#
[module/wifi]
type = custom/script
exec = nmcli -t -f WIFI general | sed 's/^enabled//;s/^disabled/睊/' # Icons: enabled -> , disabled -> 睊

# click-left = ~/.config/polybar/scripts/wifi-menu.sh
click-left = ~/bin/wifi-menu.sh
interval = 10
