require("user.options")
require("user.plugins")
require("user.colorscheme")
require("user.cmp")
require("user.lsp")
require("user.telescope")

require("user.luasnip")

require("user.gitsigns")
require("user.treesitter")
require("user.autopairs")
require("user.neoai")
require("user.comment")
require("user.nvim-tree")
require("user.bufferline")
require("user.lualine")
require("user.toggleterm")
require("user.project")
require("user.impatient")
require("user.indentline")
require("user.alpha")
require("user.whichkey")
require("user.autocommands")
require("user.neoscroll")
require("user.go")
require("user.nvim-dap-virtual-text")
require("user.terraform")
--
-- Always load keymaps last
require("user.keymaps")
