require("user.options")
require("user.plugins")
-- require("user.plugins-lazy")
-- require("user.colorscheme")
require("user.themes.catppuccin")
require("user.cmp")
require("user.lsp")
require("user.telescope")
require("user.luasnip")
require("user.gitsigns")
require("user.treesitter")
require("user.nvim-tree")
require("user.neoscroll")
require("user.comment")
require("user.autopairs")
require("user.bufferline")
require("user.lualine")
require("user.alpha")
require("user.indentline")
require("user.autocommands")
require("user.avante")
-- require("user.nvim-dap-go")
require("user.nvim-dap-virtual-text")

require("user.neoai")
require("user.go")
require("user.terraform")
--
-- Always load keymaps last
require("user.keymaps")
